/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_android_blue_smarthomefunc_jninative_SmartHomeNativeUtils */

#ifndef _Included_com_android_blue_smarthomefunc_jninative_SmartHomeNativeUtils
#define _Included_com_android_blue_smarthomefunc_jninative_SmartHomeNativeUtils
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_android_blue_smarthomefunc_jninative_SmartHomeNativeUtils
 * Method:    initPath
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_android_blue_smarthomefunc_jninative_SmartHomeNativeUtils_initPath
  (JNIEnv *, jclass, jstring);

/*
 * Class:     com_android_blue_smarthomefunc_jninative_SmartHomeNativeUtils
 * Method:    save
 * Signature: (Ljava/lang/String;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_android_blue_smarthomefunc_jninative_SmartHomeNativeUtils_save
  (JNIEnv *, jclass, jstring, jstring);

/*
 * Class:     com_android_blue_smarthomefunc_jninative_SmartHomeNativeUtils
 * Method:    verify
 * Signature: (Ljava/lang/String;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_android_blue_smarthomefunc_jninative_SmartHomeNativeUtils_verify
  (JNIEnv *, jclass, jstring, jstring);

/*
 * Class:     com_android_blue_smarthomefunc_jninative_SmartHomeNativeUtils
 * Method:    destroy
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_android_blue_smarthomefunc_jninative_SmartHomeNativeUtils_destroy
        (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
